swagger: "2.0"
info:
  version: 1.0.0
  title: openweathermap-swagger
  description: A sample API
  contact:
    name: Swagger API Team
    email: john@boats.io
    url: "https://github.com/johndcarmichael/boats/"
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: samples.openweathermap.org
basePath: /data/2.5
schemes:
  - https
tags:
  - name: weather
    description: Weather data
securityDefinitions:
  jwtToken:
    type: apiKey
    name: Authorization
    in: header
  apiKeyAdmin:
    type: apiKey
    name: x-api-key
    in: header
  basic:
    type: http
    scheme: basic
paths:
  /weather/:
    get:
      tags:
        - weather
      summary: Get weather
      description: Query with varying content
      operationId: weatherGet
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/queryAppId"
        - $ref: "#/parameters/queryCountry"
        - $ref: "#/parameters/queryId"
        - $ref: "#/parameters/queryPlanet"
        - $ref: "#/parameters/queryLat"
        - $ref: "#/parameters/queryLon"
        - $ref: "#/parameters/headerSearchId"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Weather"
        "400":
          description: Invalid Identifier supplied
        "404":
          description: Round not found
      security:
        - apiKeyAdmin: []
        - jwtToken: []
        - basic: []
      x-passRequest: true
  /weather/{id}:
    get:
      tags:
        - weather
      summary: Get weather
      description: Query with varying content
      operationId: weatherIdGet
      x-permission: getWeatherDetail
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/pathId"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/WeatherFull"
        "400":
          description: Invalid Identifier supplied
        "404":
          description: Round not found
      security:
        - apiKeyAdmin: []
        - jwtToken: []
      x-passThruWithoutJWT: true
  /rain/:
    get:
      tags:
        - weather
      summary: Get weather
      description: Query with varying content
      operationId: rainGet
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/queryCountry"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Weather"
        "400":
          description: Invalid Identifier supplied
        "404":
          description: Round not found
    post:
      tags:
        - weather
      summary: Get weather
      description: Query with varying content
      operationId: rainPost
      produces:
        - application/json
      parameters:
        - in: body
          name: createRain
          required: true
          schema:
            $ref: "#/definitions/Coord"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Weather"
        "400":
          description: Invalid Identifier supplied
        "404":
          description: Round not found
      x-passRequest: true
    put:
      tags:
        - weather
      summary: Get weather
      description: Query with varying content
      operationId: rainPut
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/formDataImage"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Weather"
        "400":
          description: Invalid Identifier supplied
        "404":
          description: Round not found
      x-passResponse: true
parameters:
  formDataImage:
    in: formData
    name: image
    type: file
    description: An image to upload
    required: true
  pathId:
    in: path
    name: id
    required: true
    type: string
  queryAppId:
    in: query
    name: appid
    required: true
    type: string
    description: |
      Grab a free API key from here: https://openweathermap.org/price
  queryCountry:
    in: query
    name: q
    required: false
    type: string
    description: >
      q city name and country code divided by comma, use ISO 3166 country codes.
      for example: q=London,uk or just q=London
  queryId:
    in: query
    name: id
    required: false
    type: number
    description: >
      City ID based on city.list.json.gz can be downloaded here
      http://bulk.openweathermap.org/sample/
  queryLat:
    in: query
    name: lat
    required: false
    type: number
    description: |
      Needs to be paired with lon
  queryLon:
    in: query
    name: lon
    required: false
    type: number
    description: |
      Needs to be paired with lat
  queryPlanet:
    in: query
    name: planet
    required: false
    type: string
    description: |
      Needs to be paired with lat
    enum:
      - Earth
      - Mars
  headerSearchId:
    in: header
    name: Search-Id
    type: string
    description: Unique search id
    pattern: ^Bearer .+$
    x-example: 569eecd9-9962-4aed-a0f0-30476c6a82ed
definitions:
  AdditionalProps:
    type: object
    additionalProperties:
      type: string
  ArrayProps:
    type: array
    items:
      type: string
  Coord:
    type: object
    properties:
      lon:
        type: number
      lat:
        type: number
      planet:
        type: string
        enum:
          - Earth
          - Mars
  JwtAccess:
    type: object
    description: >
      This model will never be passed in this from the front and backend or vice
      versa. This represents the payload of the access jwt token.
    properties:
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      username:
        type: string
      rid:
        type: string
  WeatherFull:
    allOf:
      - $ref: "#/definitions/Weather"
      - type: object
        required:
          - name
        properties:
          id:
            type: string
          name:
            type: string
  Weather:
    type: object
    required:
      - coord
    properties:
      coord:
        $ref: "#/definitions/Coord"
      weather:
        type: array
        items:
          type: object
          properties:
            id:
              type: number
            main:
              type: string
            description:
              type: string
            icon:
              type: string
      base:
        type: string
      main:
        type: object
        properties:
          temp:
            type: number
          pressure:
            type: number
          humidity:
            type: number
          temp_min:
            type: number
          temp_max:
            type: number
          sea_level:
            type: number
          grnd_level:
            type: number
      wind:
        type: object
        properties:
          speed:
            type: number
          deg:
            type: number
          clouds:
            type: object
            properties:
              all:
                type: number
      dt:
        type: number
      sys:
        type: object
        properties:
          message:
            type: number
          country:
            type: string
          sunrise:
            type: number
          sunset:
            type: number
      id:
        type: number
      name:
        type: string
      cod:
        type: number
